apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::043309343189:role/eks-nodes-role
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::043309343189:role/ssm-role
      username: jenkins-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

